# Generated by Django 4.1.13 on 2023-11-27 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("widget", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="widget",
            old_name="layout",
            new_name="size",
        ),
        migrations.RemoveField(
            model_name="theme",
            name="widget",
        ),
        migrations.AddField(
            model_name="widget",
            name="theme",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="widget.theme",
            ),
        ),
    ]
