# Generated by Django 4.1.13 on 2023-11-29 16:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("widget", "0003_rename_fsm_name_widget_fsm_def_remove_widget_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="widget",
            name="temp_id",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
