# Generated by Django 4.1.13 on 2023-11-29 16:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("widget", "0004_widget_temp_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="widget",
            name="id",
        ),
        migrations.AlterField(
            model_name="widget",
            name="temp_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
