# Generated by Django 4.1.13 on 2023-11-29 16:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("widget", "0005_remove_widget_id_alter_widget_temp_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="widget",
            old_name="temp_id",
            new_name="id",
        ),
    ]
