# Generated by Django 4.1.13 on 2024-04-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("widget", "0007_alter_theme_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="widget",
            name="display_generation",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="widget",
            name="display_sources",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="widget",
            name="sources_first",
            field=models.BooleanField(default=False),
        ),
    ]
