# Generated by Django 4.1.13 on 2024-06-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("widget", "0008_widget_display_generation_widget_display_sources_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="theme",
            name="data",
            field=models.JSONField(
                default={
                    "chatfaq-color-alertMessage-text": {
                        "dark": "#e7e8e9",
                        "light": "#545a64",
                    },
                    "chatfaq-color-bubbleButton-background": "linear-gradient(135deg, #CE0578 0%, #463075 100%)",
                    "chatfaq-color-bubbleButton-background-hover": "linear-gradient(135deg, #463075 0%, #220D44 100%)",
                    "chatfaq-color-chat-background": {
                        "dark": "#4D4160",
                        "light": "#dfdaea",
                    },
                    "chatfaq-color-chatInput-background": {
                        "dark": "#3c2d52",
                        "light": "#cac2da",
                    },
                    "chatfaq-color-chatInput-border": {
                        "dark": "#1A0438",
                        "light": "#9a8eb5",
                    },
                    "chatfaq-color-chatInput-text": {
                        "dark": "#FFFFFF",
                        "light": "#020C1C",
                    },
                    "chatfaq-color-chatMessageBot-background": {
                        "dark": "#3c2d52",
                        "light": "#cac2da",
                    },
                    "chatfaq-color-chatMessageBot-text": {
                        "dark": "#FFFFFF",
                        "light": "#020C1C",
                    },
                    "chatfaq-color-chatMessageHuman-background": {
                        "dark": "#1A0438",
                        "light": "#463075",
                    },
                    "chatfaq-color-chatMessageHuman-text": {
                        "dark": "#FFFFFF",
                        "light": "#FFFFFF",
                    },
                    "chatfaq-color-chatMessageReference-background": {
                        "dark": "#1A0438",
                        "light": "#4630751a",
                    },
                    "chatfaq-color-chatMessageReference-text": {
                        "dark": "#dfdaea",
                        "light": "#463075",
                    },
                    "chatfaq-color-chatMessageReferenceTitle-text": {
                        "dark": "#aaafb5",
                        "light": "#9a8eb5",
                    },
                    "chatfaq-color-chatPlaceholder-text": {
                        "dark": "#dfdaea",
                        "light": "#020c1c99",
                    },
                    "chatfaq-color-clipboard-text": {
                        "dark": "#cac2da",
                        "light": "#9a8eb5",
                    },
                    "chatfaq-color-darkFilter": "#020c1cb3",
                    "chatfaq-color-loader": {"dark": "#FFFFFF", "light": "#463075"},
                    "chatfaq-color-menu-background": "linear-gradient(135deg, #463075 0%, #220D44 100%)",
                    "chatfaq-color-menu-border": "#4D4160",
                    "chatfaq-color-menu-scrollColor": "#9FFFFF",
                    "chatfaq-color-menu-text": "#FFFFFF",
                    "chatfaq-color-menuButton-background": "#463075",
                    "chatfaq-color-menuItem-background": "#dfdaea1a",
                    "chatfaq-color-menuItem-background-hover": "#1A0438",
                    "chatfaq-color-menuItem-border-edit": "#9FFFFF",
                    "chatfaq-color-scrollBar": {"dark": "#463075", "light": "#FFFFFF"},
                    "chatfaq-color-separator": {
                        "dark": "#4D4160",
                        "light": "#46307533",
                    },
                    "chatfaq-font-body-m": "normal normal 400 24px/33px 'Open Sans'",
                    "chatfaq-font-body-m-bold": "normal normal 600 16px/22px 'Open Sans'",
                    "chatfaq-font-body-s": "normal normal 400 14px/19px 'Open Sans'",
                    "chatfaq-font-body-xl": "normal normal 400 24px/33px 'Open Sans'",
                    "chatfaq-font-body-xs": "normal normal 400 14px/19px 'Open Sans'",
                    "chatfaq-font-button": "normal normal 600 14px/17px 'Montserrat'",
                    "chatfaq-font-caption-md": "italic normal 600 14px/19px 'Open Sans'",
                    "chatfaq-font-caption-sm": "normal normal 400 12px/16px 'Open Sans'",
                    "chatfaq-size-bubbleButton": "60px",
                }
            ),
        ),
    ]
