# Generated by Django 4.1.13 on 2024-10-04 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("widget", "0010_alter_theme_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalWidget",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("domain", models.URLField()),
                ("fsm_def", models.CharField(max_length=255)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("subtitle", models.CharField(blank=True, max_length=255, null=True)),
                ("fullScreen", models.BooleanField(default=False)),
                ("maximized", models.BooleanField(default=False)),
                ("history_opened", models.BooleanField(default=False)),
                ("manage_user_id", models.BooleanField(default=True)),
                ("display_generation", models.BooleanField(default=True)),
                ("display_sources", models.BooleanField(default=True)),
                ("sources_first", models.BooleanField(default=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="widget.theme",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical widget",
                "verbose_name_plural": "historical widgets",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalTheme",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "data",
                    models.JSONField(
                        default={
                            "chatfaq-arrow-down-icon-color": "#FFFFFF",
                            "chatfaq-burger-menu-icon-color": "#FFFFFF",
                            "chatfaq-check-icon-color-dark": "#FFFFFF",
                            "chatfaq-check-icon-color-light": "#FFFFFF",
                            "chatfaq-checkbox-checked-icon-color": "#FFFFFF",
                            "chatfaq-checkbox-icon-color": "#FFFFFF",
                            "chatfaq-close-icon-color": "#FFFFFF",
                            "chatfaq-color-alertMessage-text": {
                                "dark": "#e7e8e9",
                                "light": "#545a64",
                            },
                            "chatfaq-color-bubbleButton-background": "linear-gradient(135deg, #CE0578 0%, #463075 100%)",
                            "chatfaq-color-bubbleButton-background-hover": "linear-gradient(135deg, #463075 0%, #220D44 100%)",
                            "chatfaq-color-chat-background": {
                                "dark": "#4D4160",
                                "light": "#dfdaea",
                            },
                            "chatfaq-color-chatInput-background": {
                                "dark": "#3c2d52",
                                "light": "#cac2da",
                            },
                            "chatfaq-color-chatInput-border": {
                                "dark": "#1A0438",
                                "light": "#9a8eb5",
                            },
                            "chatfaq-color-chatInput-text": {
                                "dark": "#FFFFFF",
                                "light": "#020C1C",
                            },
                            "chatfaq-color-chatMessageBot-background": {
                                "dark": "#3c2d52",
                                "light": "#cac2da",
                            },
                            "chatfaq-color-chatMessageBot-text": {
                                "dark": "#FFFFFF",
                                "light": "#020C1C",
                            },
                            "chatfaq-color-chatMessageHuman-background": {
                                "dark": "#1A0438",
                                "light": "#463075",
                            },
                            "chatfaq-color-chatMessageHuman-text": {
                                "dark": "#FFFFFF",
                                "light": "#FFFFFF",
                            },
                            "chatfaq-color-chatMessageReference-background": {
                                "dark": "#1A0438",
                                "light": "#4630751a",
                            },
                            "chatfaq-color-chatMessageReference-text": {
                                "dark": "#dfdaea",
                                "light": "#463075",
                            },
                            "chatfaq-color-chatMessageReferenceTitle-text": {
                                "dark": "#aaafb5",
                                "light": "#9a8eb5",
                            },
                            "chatfaq-color-chatPlaceholder-text": {
                                "dark": "#dfdaea",
                                "light": "#020c1c99",
                            },
                            "chatfaq-color-clipboard-text": {
                                "dark": "#cac2da",
                                "light": "#9a8eb5",
                            },
                            "chatfaq-color-darkFilter": "#020c1cb3",
                            "chatfaq-color-loader": {
                                "dark": "#FFFFFF",
                                "light": "#463075",
                            },
                            "chatfaq-color-menu-background": "linear-gradient(135deg, #463075 0%, #220D44 100%)",
                            "chatfaq-color-menu-border": "#4D4160",
                            "chatfaq-color-menu-scrollColor": "#9FFFFF",
                            "chatfaq-color-menu-text": "#FFFFFF",
                            "chatfaq-color-menuButton-background": "#463075",
                            "chatfaq-color-menuItem-background": "#dfdaea1a",
                            "chatfaq-color-menuItem-background-hover": "#1A0438",
                            "chatfaq-color-menuItem-border-edit": "#9FFFFF",
                            "chatfaq-color-scrollBar": {
                                "dark": "#463075",
                                "light": "#FFFFFF",
                            },
                            "chatfaq-color-separator": {
                                "dark": "#4D4160",
                                "light": "#46307533",
                            },
                            "chatfaq-copy-icon-color": "#FFFFFF",
                            "chatfaq-dot-menu-hovered-icon-color": "#FFFFFF",
                            "chatfaq-dot-menu-icon-color": "#FFFFFF",
                            "chatfaq-double-arrow-left-icon-color": "#FFFFFF",
                            "chatfaq-double-arrow-right-icon-color": "#FFFFFF",
                            "chatfaq-download-icon-color": "#FFFFFF",
                            "chatfaq-edit-icon-color": "#FFFFFF",
                            "chatfaq-font-body-m": "normal normal 400 24px/33px 'Open Sans'",
                            "chatfaq-font-body-m-bold": "normal normal 600 16px/22px 'Open Sans'",
                            "chatfaq-font-body-s": "normal normal 400 14px/19px 'Open Sans'",
                            "chatfaq-font-body-xl": "normal normal 400 24px/33px 'Open Sans'",
                            "chatfaq-font-body-xs": "normal normal 400 14px/19px 'Open Sans'",
                            "chatfaq-font-button": "normal normal 600 14px/17px 'Montserrat'",
                            "chatfaq-font-caption-md": "italic normal 600 14px/19px 'Open Sans'",
                            "chatfaq-font-caption-sm": "normal normal 400 12px/16px 'Open Sans'",
                            "chatfaq-logo-icon-color": "#FFFFFF",
                            "chatfaq-logo-long-icon-color": "#FFFFFF",
                            "chatfaq-mail-icon-color": "#FFFFFF",
                            "chatfaq-maximize-icon-color": "#FFFFFF",
                            "chatfaq-menu-check-icon-color": "#FFFFFF",
                            "chatfaq-minimize-icon-color": "#FFFFFF",
                            "chatfaq-moon-icon-color": "#FFFFFF",
                            "chatfaq-plus-icon-color": "#FFFFFF",
                            "chatfaq-refresh-icon-color": "#FFFFFF",
                            "chatfaq-send-icon-color-dark": "#FFFFFF",
                            "chatfaq-send-icon-color-light": "#1A0438",
                            "chatfaq-size-bubbleButton": "60px",
                            "chatfaq-sun-icon-color": "#FFFFFF",
                            "chatfaq-thumb-down-icon-color": "#FFFFFF",
                            "chatfaq-thumb-up-icon-color": "#FFFFFF",
                            "chatfaq-trash-icon-color": "#FFFFFF",
                        }
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical theme",
                "verbose_name_plural": "historical themes",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
