# Generated by Django 4.1.13 on 2024-10-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("widget", "0011_historicalwidget_historicaltheme"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalwidget",
            old_name="fullScreen",
            new_name="full_screen",
        ),
        migrations.RenameField(
            model_name="widget",
            old_name="fullScreen",
            new_name="full_screen",
        ),
        migrations.RemoveField(
            model_name="historicalwidget",
            name="display_generation",
        ),
        migrations.RemoveField(
            model_name="historicalwidget",
            name="display_sources",
        ),
        migrations.RemoveField(
            model_name="historicalwidget",
            name="history_opened",
        ),
        migrations.RemoveField(
            model_name="historicalwidget",
            name="manage_user_id",
        ),
        migrations.RemoveField(
            model_name="historicalwidget",
            name="maximized",
        ),
        migrations.RemoveField(
            model_name="historicalwidget",
            name="theme",
        ),
        migrations.RemoveField(
            model_name="widget",
            name="display_generation",
        ),
        migrations.RemoveField(
            model_name="widget",
            name="display_sources",
        ),
        migrations.RemoveField(
            model_name="widget",
            name="history_opened",
        ),
        migrations.RemoveField(
            model_name="widget",
            name="manage_user_id",
        ),
        migrations.RemoveField(
            model_name="widget",
            name="maximized",
        ),
        migrations.RemoveField(
            model_name="widget",
            name="theme",
        ),
        migrations.AddField(
            model_name="historicalwidget",
            name="chatfaq_api",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="historicalwidget",
            name="chatfaq_ws",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="historicalwidget",
            name="custom_css",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalwidget",
            name="custom_i_dramed_msgs",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="historicalwidget",
            name="fit_to_parent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalwidget",
            name="initial_conversation_metadata",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="historicalwidget",
            name="lang",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalwidget",
            name="only_chat",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalwidget",
            name="start_small_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalwidget",
            name="start_with_history_closed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalwidget",
            name="stick_input_prompt",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="widget",
            name="chatfaq_api",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="widget",
            name="chatfaq_ws",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="widget",
            name="custom_css",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="widget",
            name="custom_i_dramed_msgs",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="widget",
            name="fit_to_parent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="widget",
            name="initial_conversation_metadata",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="widget",
            name="lang",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="widget",
            name="only_chat",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="widget",
            name="start_small_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="widget",
            name="start_with_history_closed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="widget",
            name="stick_input_prompt",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="historicaltheme",
            name="data",
            field=models.JSONField(
                default={
                    "chatfaq-arrow-down-icon-color": "#FFFFFF",
                    "chatfaq-burger-menu-icon-color": "#FFFFFF",
                    "chatfaq-check-icon-color-dark": "#FFFFFF",
                    "chatfaq-check-icon-color-light": "#FFFFFF",
                    "chatfaq-checkbox-checked-icon-color": "#FFFFFF",
                    "chatfaq-checkbox-icon-color": "#FFFFFF",
                    "chatfaq-close-icon-color": "#FFFFFF",
                    "chatfaq-color-alertMessage-text": {
                        "dark": "#e7e8e9",
                        "light": "#545a64",
                    },
                    "chatfaq-color-bubbleButton-background": "linear-gradient(135deg, #CE0578 0%, #463075 100%)",
                    "chatfaq-color-bubbleButton-background-hover": "linear-gradient(135deg, #463075 0%, #220D44 100%)",
                    "chatfaq-color-chat-background": {
                        "dark": "#4D4160",
                        "light": "#dfdaea",
                    },
                    "chatfaq-color-chatInput-background": {
                        "dark": "#3c2d52",
                        "light": "#cac2da",
                    },
                    "chatfaq-color-chatInput-border": {
                        "dark": "#1A0438",
                        "light": "#9a8eb5",
                    },
                    "chatfaq-color-chatInput-text": {
                        "dark": "#FFFFFF",
                        "light": "#020C1C",
                    },
                    "chatfaq-color-chatMessageBot-background": {
                        "dark": "#3c2d52",
                        "light": "#cac2da",
                    },
                    "chatfaq-color-chatMessageBot-text": {
                        "dark": "#FFFFFF",
                        "light": "#020C1C",
                    },
                    "chatfaq-color-chatMessageHuman-background": {
                        "dark": "#1A0438",
                        "light": "#463075",
                    },
                    "chatfaq-color-chatMessageHuman-text": {
                        "dark": "#FFFFFF",
                        "light": "#FFFFFF",
                    },
                    "chatfaq-color-chatMessageReference-background": {
                        "dark": "#1A0438",
                        "light": "#4630751a",
                    },
                    "chatfaq-color-chatMessageReference-text": {
                        "dark": "#dfdaea",
                        "light": "#463075",
                    },
                    "chatfaq-color-chatMessageReferenceTitle-text": {
                        "dark": "#aaafb5",
                        "light": "#9a8eb5",
                    },
                    "chatfaq-color-chatPlaceholder-text": {
                        "dark": "#dfdaea",
                        "light": "#020c1c99",
                    },
                    "chatfaq-color-darkFilter": "#020c1cb3",
                    "chatfaq-color-loader": {"dark": "#FFFFFF", "light": "#463075"},
                    "chatfaq-color-menu-background": "linear-gradient(135deg, #463075 0%, #220D44 100%)",
                    "chatfaq-color-menu-border": "#4D4160",
                    "chatfaq-color-menu-scrollColor": "#9FFFFF",
                    "chatfaq-color-menu-text": "#FFFFFF",
                    "chatfaq-color-menuButton-background": "#463075",
                    "chatfaq-color-menuItem-background": "#dfdaea1a",
                    "chatfaq-color-menuItem-background-hover": "#1A0438",
                    "chatfaq-color-menuItem-border-edit": "#9FFFFF",
                    "chatfaq-color-scrollBar": {"dark": "#463075", "light": "#FFFFFF"},
                    "chatfaq-color-separator": {
                        "dark": "#4D4160",
                        "light": "#46307533",
                    },
                    "chatfaq-color-thumbs-and-clipboard": {
                        "dark": "#cac2da",
                        "light": "#9a8eb5",
                    },
                    "chatfaq-copy-icon-color": "#FFFFFF",
                    "chatfaq-dot-menu-hovered-icon-color": "#FFFFFF",
                    "chatfaq-dot-menu-icon-color": "#FFFFFF",
                    "chatfaq-double-arrow-left-icon-color": "#FFFFFF",
                    "chatfaq-double-arrow-right-icon-color": "#FFFFFF",
                    "chatfaq-download-icon-color": "#FFFFFF",
                    "chatfaq-edit-icon-color": "#FFFFFF",
                    "chatfaq-font-body-m": "normal normal 400 24px/33px 'Open Sans'",
                    "chatfaq-font-body-m-bold": "normal normal 600 16px/22px 'Open Sans'",
                    "chatfaq-font-body-s": "normal normal 400 14px/19px 'Open Sans'",
                    "chatfaq-font-body-xl": "normal normal 400 24px/33px 'Open Sans'",
                    "chatfaq-font-body-xs": "normal normal 400 14px/19px 'Open Sans'",
                    "chatfaq-font-button": "normal normal 600 14px/17px 'Montserrat'",
                    "chatfaq-font-caption-md": "italic normal 600 14px/19px 'Open Sans'",
                    "chatfaq-font-caption-sm": "normal normal 400 12px/16px 'Open Sans'",
                    "chatfaq-logo-icon-color": "#FFFFFF",
                    "chatfaq-logo-long-icon-color": "#FFFFFF",
                    "chatfaq-mail-icon-color": "#FFFFFF",
                    "chatfaq-maximize-icon-color": "#FFFFFF",
                    "chatfaq-menu-check-icon-color": "#FFFFFF",
                    "chatfaq-minimize-icon-color": "#FFFFFF",
                    "chatfaq-moon-icon-color": "#FFFFFF",
                    "chatfaq-plus-icon-color": "#FFFFFF",
                    "chatfaq-refresh-icon-color": "#FFFFFF",
                    "chatfaq-send-icon-color-dark": "#FFFFFF",
                    "chatfaq-send-icon-color-light": "#1A0438",
                    "chatfaq-size-bubbleButton": "60px",
                    "chatfaq-sun-icon-color": "#FFFFFF",
                    "chatfaq-trash-icon-color": "#FFFFFF",
                }
            ),
        ),
        migrations.AlterField(
            model_name="historicalwidget",
            name="fsm_def",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="theme",
            name="data",
            field=models.JSONField(
                default={
                    "chatfaq-arrow-down-icon-color": "#FFFFFF",
                    "chatfaq-burger-menu-icon-color": "#FFFFFF",
                    "chatfaq-check-icon-color-dark": "#FFFFFF",
                    "chatfaq-check-icon-color-light": "#FFFFFF",
                    "chatfaq-checkbox-checked-icon-color": "#FFFFFF",
                    "chatfaq-checkbox-icon-color": "#FFFFFF",
                    "chatfaq-close-icon-color": "#FFFFFF",
                    "chatfaq-color-alertMessage-text": {
                        "dark": "#e7e8e9",
                        "light": "#545a64",
                    },
                    "chatfaq-color-bubbleButton-background": "linear-gradient(135deg, #CE0578 0%, #463075 100%)",
                    "chatfaq-color-bubbleButton-background-hover": "linear-gradient(135deg, #463075 0%, #220D44 100%)",
                    "chatfaq-color-chat-background": {
                        "dark": "#4D4160",
                        "light": "#dfdaea",
                    },
                    "chatfaq-color-chatInput-background": {
                        "dark": "#3c2d52",
                        "light": "#cac2da",
                    },
                    "chatfaq-color-chatInput-border": {
                        "dark": "#1A0438",
                        "light": "#9a8eb5",
                    },
                    "chatfaq-color-chatInput-text": {
                        "dark": "#FFFFFF",
                        "light": "#020C1C",
                    },
                    "chatfaq-color-chatMessageBot-background": {
                        "dark": "#3c2d52",
                        "light": "#cac2da",
                    },
                    "chatfaq-color-chatMessageBot-text": {
                        "dark": "#FFFFFF",
                        "light": "#020C1C",
                    },
                    "chatfaq-color-chatMessageHuman-background": {
                        "dark": "#1A0438",
                        "light": "#463075",
                    },
                    "chatfaq-color-chatMessageHuman-text": {
                        "dark": "#FFFFFF",
                        "light": "#FFFFFF",
                    },
                    "chatfaq-color-chatMessageReference-background": {
                        "dark": "#1A0438",
                        "light": "#4630751a",
                    },
                    "chatfaq-color-chatMessageReference-text": {
                        "dark": "#dfdaea",
                        "light": "#463075",
                    },
                    "chatfaq-color-chatMessageReferenceTitle-text": {
                        "dark": "#aaafb5",
                        "light": "#9a8eb5",
                    },
                    "chatfaq-color-chatPlaceholder-text": {
                        "dark": "#dfdaea",
                        "light": "#020c1c99",
                    },
                    "chatfaq-color-darkFilter": "#020c1cb3",
                    "chatfaq-color-loader": {"dark": "#FFFFFF", "light": "#463075"},
                    "chatfaq-color-menu-background": "linear-gradient(135deg, #463075 0%, #220D44 100%)",
                    "chatfaq-color-menu-border": "#4D4160",
                    "chatfaq-color-menu-scrollColor": "#9FFFFF",
                    "chatfaq-color-menu-text": "#FFFFFF",
                    "chatfaq-color-menuButton-background": "#463075",
                    "chatfaq-color-menuItem-background": "#dfdaea1a",
                    "chatfaq-color-menuItem-background-hover": "#1A0438",
                    "chatfaq-color-menuItem-border-edit": "#9FFFFF",
                    "chatfaq-color-scrollBar": {"dark": "#463075", "light": "#FFFFFF"},
                    "chatfaq-color-separator": {
                        "dark": "#4D4160",
                        "light": "#46307533",
                    },
                    "chatfaq-color-thumbs-and-clipboard": {
                        "dark": "#cac2da",
                        "light": "#9a8eb5",
                    },
                    "chatfaq-copy-icon-color": "#FFFFFF",
                    "chatfaq-dot-menu-hovered-icon-color": "#FFFFFF",
                    "chatfaq-dot-menu-icon-color": "#FFFFFF",
                    "chatfaq-double-arrow-left-icon-color": "#FFFFFF",
                    "chatfaq-double-arrow-right-icon-color": "#FFFFFF",
                    "chatfaq-download-icon-color": "#FFFFFF",
                    "chatfaq-edit-icon-color": "#FFFFFF",
                    "chatfaq-font-body-m": "normal normal 400 24px/33px 'Open Sans'",
                    "chatfaq-font-body-m-bold": "normal normal 600 16px/22px 'Open Sans'",
                    "chatfaq-font-body-s": "normal normal 400 14px/19px 'Open Sans'",
                    "chatfaq-font-body-xl": "normal normal 400 24px/33px 'Open Sans'",
                    "chatfaq-font-body-xs": "normal normal 400 14px/19px 'Open Sans'",
                    "chatfaq-font-button": "normal normal 600 14px/17px 'Montserrat'",
                    "chatfaq-font-caption-md": "italic normal 600 14px/19px 'Open Sans'",
                    "chatfaq-font-caption-sm": "normal normal 400 12px/16px 'Open Sans'",
                    "chatfaq-logo-icon-color": "#FFFFFF",
                    "chatfaq-logo-long-icon-color": "#FFFFFF",
                    "chatfaq-mail-icon-color": "#FFFFFF",
                    "chatfaq-maximize-icon-color": "#FFFFFF",
                    "chatfaq-menu-check-icon-color": "#FFFFFF",
                    "chatfaq-minimize-icon-color": "#FFFFFF",
                    "chatfaq-moon-icon-color": "#FFFFFF",
                    "chatfaq-plus-icon-color": "#FFFFFF",
                    "chatfaq-refresh-icon-color": "#FFFFFF",
                    "chatfaq-send-icon-color-dark": "#FFFFFF",
                    "chatfaq-send-icon-color-light": "#1A0438",
                    "chatfaq-size-bubbleButton": "60px",
                    "chatfaq-sun-icon-color": "#FFFFFF",
                    "chatfaq-trash-icon-color": "#FFFFFF",
                }
            ),
        ),
        migrations.AlterField(
            model_name="widget",
            name="fsm_def",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
