# Generated by Django 4.1.13 on 2024-10-07 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("widget", "0012_rename_fullscreen_historicalwidget_full_screen_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalwidget",
            name="chatfaq_api",
            field=models.CharField(
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid HTTP URL",
                        regex="^(http|https)://([a-zA-Z0-9.-]+(:[0-9]+)?)/?$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="historicalwidget",
            name="chatfaq_ws",
            field=models.CharField(
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a WS URL",
                        regex="^(ws|wss)://([a-zA-Z0-9.-]+(:[0-9]+)?)/?$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="widget",
            name="chatfaq_api",
            field=models.CharField(
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid HTTP URL",
                        regex="^(http|https)://([a-zA-Z0-9.-]+(:[0-9]+)?)/?$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="widget",
            name="chatfaq_ws",
            field=models.CharField(
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a WS URL",
                        regex="^(ws|wss)://([a-zA-Z0-9.-]+(:[0-9]+)?)/?$",
                    )
                ],
            ),
        ),
    ]
