# Generated by Django 4.1.13 on 2024-10-07 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "widget",
            "0014_rename_custom_i_dramed_msgs_historicalwidget_custom_i_framed_msgs_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalwidget",
            name="theme",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="widget.theme",
            ),
        ),
        migrations.AddField(
            model_name="widget",
            name="theme",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="widget.theme",
            ),
        ),
    ]
