# Generated by Django 4.1.13 on 2024-10-08 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("widget", "0015_historicalwidget_theme_widget_theme"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalwidget",
            name="chatfaq_api",
        ),
        migrations.RemoveField(
            model_name="widget",
            name="chatfaq_api",
        ),
    ]
