# Generated by Django 4.1.13 on 2024-11-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("widget", "0018_historicalwidget_allow_attachments_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalwidget",
            name="authentication_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="widget",
            name="authentication_required",
            field=models.BooleanField(default=False),
        ),
    ]
