# Generated by Django 4.2.16 on 2024-12-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("widget", "0019_historicalwidget_authentication_required_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalwidget",
            name="display_logout",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalwidget",
            name="hide_theme_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="widget",
            name="display_logout",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="widget",
            name="hide_theme_mode",
            field=models.BooleanField(default=False),
        ),
    ]
