# Generated by Django 4.2.16 on 2024-12-12 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("widget", "0020_historicalwidget_display_logout_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalwidget",
            old_name="hide_theme_mode",
            new_name="disable_day_night_mode",
        ),
        migrations.RenameField(
            model_name="historicalwidget",
            old_name="display_logout",
            new_name="enable_logout",
        ),
        migrations.RenameField(
            model_name="widget",
            old_name="hide_theme_mode",
            new_name="disable_day_night_mode",
        ),
        migrations.RenameField(
            model_name="widget",
            old_name="display_logout",
            new_name="enable_logout",
        ),
    ]
