# Generated by Django 4.2.17 on 2025-01-03 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0022_historicalwidget_enable_resend_widget_enable_resend'),
        ('widget', '0025_alter_historicaltheme_data_alter_theme_data'),
    ]

    operations = [
    ]
