# Generated by Django 4.2.17 on 2025-01-08 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0026_alter_historicaltheme_data_alter_theme_data'),
        ('widget', '0026_merge_20250102_1633'),
    ]

    operations = [
    ]
