# Generated by Django 4.2.17 on 2025-01-16 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0026_merge_20250103_1437'),
        ('widget', '0027_merge_20250108_1656'),
    ]

    operations = [
    ]
