# Generated by Django 4.2.19 on 2025-02-19 10:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("widget", "0028_merge_20250116_1007"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalwidget",
            name="speech_synthesis",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalwidget",
            name="speech_synthesis_pitch",
            field=models.FloatField(
                default=1.0,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(2.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="historicalwidget",
            name="speech_synthesis_rate",
            field=models.FloatField(
                default=1.0,
                validators=[
                    django.core.validators.MinValueValidator(0.1),
                    django.core.validators.MaxValueValidator(10.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="historicalwidget",
            name="speech_synthesis_voices",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="widget",
            name="speech_synthesis",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="widget",
            name="speech_synthesis_pitch",
            field=models.FloatField(
                default=1.0,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(2.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="widget",
            name="speech_synthesis_rate",
            field=models.FloatField(
                default=1.0,
                validators=[
                    django.core.validators.MinValueValidator(0.1),
                    django.core.validators.MaxValueValidator(10.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="widget",
            name="speech_synthesis_voices",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="widget",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("speech_synthesis_pitch__gte", 0.0),
                    ("speech_synthesis_pitch__lte", 2.0),
                ),
                name="pitch_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="widget",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("speech_synthesis_rate__gte", 0.1),
                    ("speech_synthesis_rate__lte", 10.0),
                ),
                name="rate_range",
            ),
        ),
    ]
