# Generated by Django 4.2.19 on 2025-02-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("widget", "0029_historicalwidget_speech_synthesis_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalwidget",
            name="speech_recognition_always_on",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalwidget",
            name="speech_synthesis_enabled_by_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="widget",
            name="speech_recognition_always_on",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="widget",
            name="speech_synthesis_enabled_by_default",
            field=models.BooleanField(default=False),
        ),
    ]
