# Generated by Django 4.2.19 on 2025-02-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("widget", "0030_historicalwidget_speech_recognition_always_on_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalwidget",
            name="speech_recognition_lang",
            field=models.CharField(default="en-US", max_length=255),
        ),
        migrations.AddField(
            model_name="widget",
            name="speech_recognition_lang",
            field=models.CharField(default="en-US", max_length=255),
        ),
    ]
