# Generated by Django 4.2.19 on 2025-02-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("widget", "0031_historicalwidget_speech_recognition_lang_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalwidget",
            name="speech_recognition_phrase_activation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="widget",
            name="speech_recognition_phrase_activation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
