# Generated by Django 4.2.19 on 2025-02-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "widget",
            "0032_historicalwidget_speech_recognition_phrase_activation_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalwidget",
            name="speech_recognition_beep",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="widget",
            name="speech_recognition_beep",
            field=models.BooleanField(default=False),
        ),
    ]
