# Generated by Django 4.2.19 on 2025-03-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("widget", "0034_alter_historicaltheme_data_alter_theme_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalwidget",
            name="hide_sources",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalwidget",
            name="show_tool_messages",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="widget",
            name="hide_sources",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="widget",
            name="show_tool_messages",
            field=models.BooleanField(default=False),
        ),
    ]
