# Generated by Django 4.2.19 on 2025-03-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("widget", "0035_historicalwidget_hide_sources_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalwidget",
            name="domain",
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name="widget",
            name="domain",
            field=models.CharField(max_length=2048),
        ),
    ]
