# Generated by Django 4.1.9 on 2023-05-26 13:32

import django.db.models.deletion
from django.db import migrations, models


def clear_cached_fsm(apps, scheme_editor):
    CachedFSM = apps.get_model("fsm", "CachedFSM")
    CachedFSM.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("broker", "0019_conversation_remove_message_conversation_name_and_more"),
        ("fsm", "0003_remove_fsmdefinition_funcs"),
    ]

    operations = [
        migrations.RunPython(clear_cached_fsm),
        migrations.RemoveField(
            model_name="cachedfsm",
            name="conversation_id",
        ),
        migrations.AddField(
            model_name="cachedfsm",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="broker.conversation",
            ),
            preserve_default=False,
        ),
    ]
