# Generated by Django 4.1.13 on 2024-08-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fsm", "0004_remove_cachedfsm_conversation_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fsmdefinition",
            name="initial_state_values",
            field=models.JSONField(null=True),
        ),
    ]
