# Generated by Django 4.1.13 on 2024-09-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fsm", "0005_fsmdefinition_initial_state_values"),
    ]

    operations = [
        migrations.AddField(
            model_name="cachedfsm",
            name="initial_conversation_metadata",
            field=models.JSONField(default=dict),
        ),
    ]
