# Generated by Django 4.1.13 on 2024-11-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fsm", "0006_cachedfsm_initial_conversation_metadata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cachedfsm",
            name="initial_conversation_metadata",
        ),
        migrations.AddField(
            model_name="fsmdefinition",
            name="authentication_required",
            field=models.BooleanField(default=False),
        ),
    ]
