# Generated by Django 4.1.3 on 2022-12-05 12:25

import django.db.models.deletion
import django_better_admin_arrayfield.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FiniteStateMachine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, null=True, unique=True)),
                ("definition", models.JSONField(null=True)),
                (
                    "funcs",
                    django_better_admin_arrayfield.models.fields.ArrayField(
                        base_field=models.TextField(), default=list, size=None
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CachedMachine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("conversation_id", models.CharField(max_length=255, unique=True)),
                ("current_state", models.JSONField(default=dict)),
                (
                    "fsm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fsm.finitestatemachine",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
