# Generated by Django 4.1.4 on 2023-01-11 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fsm", "0002_rename_cachedmachine_cachedfsm_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fsmdefinition",
            name="funcs",
        ),
    ]
