# Generated by Django 4.1.9 on 2023-07-03 18:31

from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):
    dependencies = [
        ("language_model", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="model",
            old_name="base_model",
            new_name="repo_id",
        ),
        migrations.AddField(
            model_name="model",
            name="ggml_model_filename",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="model",
            name="hugginface_auth_token",
            field=fernet_fields.fields.EncryptedCharField(
                blank=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="model",
            name="load_in_8bit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="model",
            name="model_config",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="model",
            name="revision",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="model",
            name="trust_remote_code_model",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="model",
            name="trust_remote_code_tokenizer",
            field=models.BooleanField(default=False),
        ),
    ]
