# Generated by Django 4.1.9 on 2023-07-04 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("language_model", "0002_rename_base_model_model_repo_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("system_prefix", models.TextField()),
                (
                    "system_tag",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "system_end",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "user_tag",
                    models.CharField(blank=True, default="<|prompt|>", max_length=255),
                ),
                (
                    "user_end",
                    models.CharField(blank=True, default="\n", max_length=255),
                ),
                (
                    "assistant_tag",
                    models.CharField(blank=True, default="<|answer|>", max_length=255),
                ),
                (
                    "assistant_end",
                    models.CharField(blank=True, default="\n", max_length=255),
                ),
                ("n_contexts_to_use", models.IntegerField(default=3)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="language_model.model",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GenerationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("top_k", models.IntegerField(default=50)),
                ("top_p", models.FloatField(default=1.0)),
                ("temperature", models.FloatField(default=1.0)),
                ("repetition_penalty", models.FloatField(default=1.0)),
                ("seed", models.IntegerField(default=42)),
                ("max_new_tokens", models.IntegerField(default=256)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="language_model.model",
                    ),
                ),
            ],
        ),
    ]
