# Generated by Django 4.1.9 on 2023-07-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("language_model", "0003_promptstructure_generationconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promptstructure",
            name="system_prefix",
            field=models.TextField(blank=True, default=""),
        ),
    ]
