# Generated by Django 4.1.9 on 2023-07-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("language_model", "0004_alter_promptstructure_system_prefix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="revision",
            field=models.CharField(
                blank=True, default="main", max_length=255, null=True
            ),
        ),
    ]
