# Generated by Django 4.1.9 on 2023-07-04 11:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("language_model", "0005_alter_model_revision"),
    ]

    operations = [
        migrations.RenameField(
            model_name="model",
            old_name="hugginface_auth_token",
            new_name="huggingface_auth_token",
        ),
    ]
