# Generated by Django 4.1.10 on 2023-07-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "language_model",
            "0006_rename_hugginface_auth_token_model_huggingface_auth_token",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="model",
            old_name="huggingface_auth_token",
            new_name="auth_token",
        ),
        migrations.AddField(
            model_name="model",
            name="use_fast_tokenizer",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="promptstructure",
            name="assistant_end",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="promptstructure",
            name="user_end",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
