# Generated by Django 4.1.10 on 2023-08-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("language_model", "0009_alter_item_context_alter_item_intent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="url",
            field=models.URLField(max_length=2083),
        ),
    ]
