# Generated by Django 4.1.10 on 2023-08-23 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("language_model", "0010_alter_item_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalPromptStructure",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("system_prefix", models.TextField(blank=True, default="")),
                (
                    "system_tag",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "system_end",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "user_tag",
                    models.CharField(blank=True, default="<|prompt|>", max_length=255),
                ),
                ("user_end", models.CharField(blank=True, default="", max_length=255)),
                (
                    "assistant_tag",
                    models.CharField(blank=True, default="<|answer|>", max_length=255),
                ),
                (
                    "assistant_end",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("n_contexts_to_use", models.IntegerField(default=3)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="language_model.model",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical prompt structure",
                "verbose_name_plural": "historical prompt structures",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
