# Generated by Django 4.1.11 on 2023-09-13 17:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("language_model", "0012_autogeneratedtitle_historicalpromptconfig_and_more"),
        ("language_model", "0015_dataset_recursive"),
    ]

    operations = []
