# Generated by Django 4.1.11 on 2023-09-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("language_model", "0016_merge_20230913_1742"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generationconfig",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
