# Generated by Django 4.1.11 on 2023-09-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("language_model", "0017_alter_generationconfig_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="llmconfig",
            old_name="ggml_model_filename",
            new_name="ggml_llm_filename",
        ),
        migrations.RemoveField(
            model_name="llmconfig",
            name="auth_token",
        ),
        migrations.RemoveField(
            model_name="llmconfig",
            name="repo_id",
        ),
        migrations.RemoveField(
            model_name="llmconfig",
            name="status",
        ),
        migrations.AddField(
            model_name="llmconfig",
            name="llm_name",
            field=models.CharField(default="gpt2", max_length=100),
        ),
        migrations.AddField(
            model_name="llmconfig",
            name="llm_type",
            field=models.CharField(
                choices=[
                    ("local_cpu", "CPU Model"),
                    ("local_gpu", "Local Model"),
                    ("vllm", "VLLM Client"),
                    ("openai", "OpenAI Model"),
                ],
                default="local",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="ragconfig",
            name="retriever_name",
            field=models.CharField(default="intfloat/e5-small-v2", max_length=255),
        ),
    ]
