# Generated by Django 4.1.11 on 2023-09-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "language_model",
            "0018_rename_ggml_model_filename_llmconfig_ggml_llm_filename_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="llmconfig",
            name="model_max_length",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="llmconfig",
            name="llm_type",
            field=models.CharField(
                choices=[
                    ("local_cpu", "Local CPU Model"),
                    ("local_gpu", "Local GPU Model"),
                    ("vllm", "VLLM Client"),
                    ("openai", "OpenAI Model"),
                ],
                default="local",
                max_length=10,
            ),
        ),
    ]
