# Generated by Django 4.1.11 on 2023-09-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("language_model", "0019_llmconfig_model_max_length_alter_llmconfig_llm_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmconfig",
            name="llm_type",
            field=models.CharField(
                choices=[
                    ("local_cpu", "Local CPU Model"),
                    ("local_gpu", "Local GPU Model"),
                    ("vllm", "VLLM Client"),
                    ("openai", "OpenAI Model"),
                ],
                default="openai",
                max_length=10,
            ),
        ),
    ]
