# Generated by Django 4.1.11 on 2023-09-20 15:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "language_model",
            "0020_retrieverconfig_remove_ragconfig_retriever_name_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="ragconfig",
            old_name="retriever",
            new_name="retriever_config",
        ),
    ]
