# Generated by Django 4.1.11 on 2023-09-20 15:24

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("language_model", "0022_rename_retriever_ragconfig_retriever_config"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="knowledgeitem",
            name="embedding",
        ),
        migrations.CreateModel(
            name="Embedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "embedding",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), blank=True, null=True, size=None
                    ),
                ),
                (
                    "knowledge_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="language_model.knowledgeitem",
                    ),
                ),
                (
                    "rag_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="language_model.ragconfig",
                    ),
                ),
            ],
        ),
    ]
