from pgvector.django import VectorExtension
from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ("language_model", "0024_autogeneratedtitle_created_date_and_more"),
    ]
    operations = [
        VectorExtension()
    ]