# Generated by Django 4.1.11 on 2023-10-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("language_model", "0024_autogeneratedtitle_created_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgebase",
            name="content_index_col",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="knowledgebase",
            name="csv_header",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="knowledgebase",
            name="page_number_index_col",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="knowledgebase",
            name="role_index_col",
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name="knowledgebase",
            name="section_index_col",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="knowledgebase",
            name="title_index_col",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="knowledgebase",
            name="url_index_col",
            field=models.IntegerField(default=2),
        ),
    ]
