# Generated by Django 4.1.11 on 2023-09-29 10:32

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):
    dependencies = [
        ("language_model", "0025_enable_pgvector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autogeneratedtitle",
            name="embedding",
            field=pgvector.django.VectorField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="embedding",
            name="embedding",
            field=pgvector.django.VectorField(blank=True, null=True),
        ),
    ]
