# Generated by Django 4.1.11 on 2023-10-18 10:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("language_model", "0025_knowledgebase_content_index_col_and_more"),
        ("language_model", "0026_alter_autogeneratedtitle_embedding_and_more"),
    ]

    operations = []
