# Generated by Django 4.1.12 on 2023-10-24 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("broker", "0026_rename_rpcconsumerroundrobinqueue_consumerroundrobinqueue"),
        ("language_model", "0027_merge_20231018_1054"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generationconfig",
            name="temperature",
            field=models.FloatField(default=0.2),
        ),
        migrations.AlterField(
            model_name="llmconfig",
            name="llm_type",
            field=models.CharField(
                choices=[
                    ("local_cpu", "Local CPU Model"),
                    ("local_gpu", "Local GPU Model"),
                    ("vllm", "VLLM Client"),
                    ("openai", "OpenAI Model"),
                ],
                default="local_gpu",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="MessageKnowledgeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("similarity", models.FloatField(blank=True, null=True)),
                ("valid", models.BooleanField(default=False)),
                (
                    "knowledge_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="language_model.knowledgeitem",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="broker.message"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Intent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("intent_name", models.CharField(max_length=255, unique=True)),
                ("auto_generated", models.BooleanField(default=False)),
                ("valid", models.BooleanField(default=False)),
                ("new_intent", models.BooleanField(default=False)),
                ("message", models.ManyToManyField(blank=True, to="broker.message")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="knowledgeitem",
            name="message",
            field=models.ManyToManyField(
                through="language_model.MessageKnowledgeItem", to="broker.message"
            ),
        ),
    ]
