# Generated by Django 4.1.12 on 2023-10-27 13:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("language_model", "0028_alter_generationconfig_temperature_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="intent",
            old_name="new_intent",
            new_name="suggested_intent",
        ),
    ]
