# Generated by Django 4.1.12 on 2023-10-30 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("language_model", "0029_rename_new_intent_intent_suggested_intent"),
    ]

    operations = [
        migrations.AddField(
            model_name="intent",
            name="knowledge_base",
            field=models.ForeignKey(
                default=5,
                on_delete=django.db.models.deletion.CASCADE,
                to="language_model.knowledgebase",
            ),
            preserve_default=False,
        ),
    ]
