# Generated by Django 4.1.12 on 2023-10-31 17:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("language_model", "0031_intent_knowledge_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="intent",
            name="knowledge_base",
        ),
    ]
