# Generated by Django 4.1.13 on 2023-12-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("language_model", "0033_alter_llmconfig_llm_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="ragconfig",
            name="disabled",
            field=models.BooleanField(default=False),
        ),
    ]
