# Generated by Django 4.1.13 on 2024-01-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("language_model", "0035_alter_generationconfig_max_new_tokens_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmconfig",
            name="llm_type",
            field=models.CharField(
                choices=[
                    ("local_cpu", "Local CPU Model"),
                    ("local_gpu", "Local GPU Model"),
                    ("vllm", "VLLM Client"),
                    ("openai", "OpenAI Model"),
                    ("claude", "Claude Model"),
                    ("mistral", "Mistral Model"),
                ],
                default="local_gpu",
                max_length=10,
            ),
        ),
    ]
