# Generated by Django 4.1.13 on 2024-01-23 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("broker", "0033_remotesdkparsers"),
        ("language_model", "0036_alter_llmconfig_llm_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgebase",
            name="parser",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="broker.remotesdkparsers",
            ),
        ),
    ]
