# Generated by Django 4.1.13 on 2024-01-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("language_model", "0037_knowledgebase_parser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledgebase",
            name="parser",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
