# Generated by Django 4.1.13 on 2024-01-25 16:30

import back.apps.language_model.models.data
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("language_model", "0038_alter_knowledgebase_parser"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgeitem",
            name="metadata",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="knowledgeitem",
            name="url",
            field=models.URLField(max_length=2083, null=True),
        ),
        migrations.CreateModel(
            name="KnowledgeItemImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_file",
                    models.FileField(
                        blank=True,
                        upload_to=back.apps.language_model.models.data.upload_to_uuid,
                    ),
                ),
                ("image_caption", models.TextField(blank=True, null=True)),
                (
                    "knowledge_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="language_model.knowledgeitem",
                    ),
                ),
            ],
        ),
    ]
