# Generated by Django 4.1.13 on 2024-01-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "language_model",
            "0039_knowledgeitem_metadata_alter_knowledgeitem_url_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="retrieverconfig",
            name="retriever_type",
            field=models.CharField(
                choices=[
                    ("colbert", "ColBERT Search"),
                    ("e5", "Standard Semantic Search"),
                ],
                default="colbert",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="retrieverconfig",
            name="model_name",
            field=models.CharField(default="colbert-ir/colbertv2.0", max_length=255),
        ),
    ]
