# Generated by Django 4.1.13 on 2024-01-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "language_model",
            "0039_knowledgeitem_metadata_alter_knowledgeitem_url_and_more",
        ),
    ]

    operations = [
        # Add the field without a default to avoid affecting existing rows
        migrations.AddField(
            model_name="retrieverconfig",
            name="retriever_type",
            field=models.CharField(
                choices=[
                    ("colbert", "ColBERT Search"),
                    ("e5", "Standard Semantic Search"),
                ],
                max_length=10,
                null=True,  # Temporarily allow null to add the column without a default
            ),
        ),
        # Run a Python operation to update existing rows to 'e5'
        migrations.RunPython(
            code=lambda apps, schema_editor: apps.get_model("language_model", "retrieverconfig").objects.update(retriever_type="e5"),
            reverse_code=migrations.RunPython.noop,  # Define how to reverse this operation if needed
        ),
        # Alter the field to set the default for new instances and disallow null
        migrations.AlterField(
            model_name="retrieverconfig",
            name="retriever_type",
            field=models.CharField(
                choices=[
                    ("colbert", "ColBERT Search"),
                    ("e5", "Standard Semantic Search"),
                ],
                default="colbert",
                max_length=10,
                null=False,  # Ensure the field cannot be null
            ),
        ),
        migrations.AlterField(
            model_name="retrieverconfig",
            name="model_name",
            field=models.CharField(default="colbert-ir/colbertv2.0", max_length=255),
        ),
    ]
