# Generated by Django 4.1.13 on 2024-01-29 16:50

import back.apps.language_model.models.data
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "language_model",
            "0039_knowledgeitem_metadata_alter_knowledgeitem_url_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledgeitemimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                upload_to=back.apps.language_model.models.data.upload_to_uuid,
            ),
        ),
    ]
