# Generated by Django 4.1.13 on 2024-01-29 17:55

import back.apps.language_model.models.data
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("language_model", "0040_alter_knowledgeitemimage_image_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledgeitemimage",
            name="image_file",
            field=models.ImageField(
                upload_to=back.apps.language_model.models.data.upload_to_uuid
            ),
        ),
    ]
