# Generated by Django 4.1.13 on 2024-01-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("language_model", "0040_retrieverconfig_retriever_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ragconfig",
            name="index_up_to_date",
            field=models.BooleanField(default=False),
        ),
    ]
