# Generated by Django 4.1.13 on 2024-01-31 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("language_model", "0041_ragconfig_index_up_to_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="ragconfig",
            name="s3_index_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
