# Generated by Django 4.1.13 on 2024-01-30 18:20

import back.apps.language_model.models.data
import back.config.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("language_model", "0041_alter_knowledgeitemimage_image_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledgebase",
            name="original_csv",
            field=models.FileField(
                blank=True,
                null=True,
                storage=back.config.storage_backends.PrivateMediaStorage(),
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="original_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                storage=back.config.storage_backends.PrivateMediaStorage(),
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgeitemimage",
            name="image_file",
            field=models.ImageField(
                storage=back.config.storage_backends.PrivateMediaStorage(),
                upload_to=back.apps.language_model.models.data.upload_to_uuid,
            ),
        ),
    ]
