# Generated by Django 4.1.13 on 2024-02-02 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("language_model", "0042_alter_knowledgebase_original_csv_and_more"),
        ("language_model", "0042_ragconfig_s3_index_path"),
    ]

    operations = []
