# Generated by Django 4.1.13 on 2024-02-05 16:45

import back.config.storage_backends
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("language_model", "0043_merge_20240202_1212"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="knowledgebase",
            name="chunk_overlap",
        ),
        migrations.RemoveField(
            model_name="knowledgebase",
            name="chunk_size",
        ),
        migrations.RemoveField(
            model_name="knowledgebase",
            name="content_index_col",
        ),
        migrations.RemoveField(
            model_name="knowledgebase",
            name="csv_header",
        ),
        migrations.RemoveField(
            model_name="knowledgebase",
            name="original_csv",
        ),
        migrations.RemoveField(
            model_name="knowledgebase",
            name="original_pdf",
        ),
        migrations.RemoveField(
            model_name="knowledgebase",
            name="original_url",
        ),
        migrations.RemoveField(
            model_name="knowledgebase",
            name="page_number_index_col",
        ),
        migrations.RemoveField(
            model_name="knowledgebase",
            name="parser",
        ),
        migrations.RemoveField(
            model_name="knowledgebase",
            name="recursive",
        ),
        migrations.RemoveField(
            model_name="knowledgebase",
            name="role_index_col",
        ),
        migrations.RemoveField(
            model_name="knowledgebase",
            name="section_index_col",
        ),
        migrations.RemoveField(
            model_name="knowledgebase",
            name="splitter",
        ),
        migrations.RemoveField(
            model_name="knowledgebase",
            name="strategy",
        ),
        migrations.RemoveField(
            model_name="knowledgebase",
            name="title_index_col",
        ),
        migrations.RemoveField(
            model_name="knowledgebase",
            name="url_index_col",
        ),
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("csv_header", models.BooleanField(default=True)),
                ("title_index_col", models.IntegerField(default=0)),
                ("content_index_col", models.IntegerField(default=1)),
                ("url_index_col", models.IntegerField(default=2)),
                ("section_index_col", models.IntegerField(default=3)),
                ("role_index_col", models.IntegerField(default=4)),
                ("page_number_index_col", models.IntegerField(default=5)),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("auto", "Auto"),
                            ("fast", "Fast"),
                            ("ocr_only", "OCR Only"),
                            ("hi_res", "Hi Res"),
                        ],
                        default="fast",
                        max_length=10,
                    ),
                ),
                ("recursive", models.BooleanField(default=True)),
                (
                    "splitter",
                    models.CharField(
                        choices=[
                            ("sentences", "Sentences"),
                            ("words", "Words"),
                            ("tokens", "Tokens"),
                            ("smart", "Smart"),
                        ],
                        default="sentences",
                        max_length=10,
                    ),
                ),
                ("chunk_size", models.IntegerField(default=128)),
                ("chunk_overlap", models.IntegerField(default=16)),
                (
                    "original_csv",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=back.config.storage_backends.PrivateMediaS3Storage(),
                        upload_to="",
                    ),
                ),
                (
                    "original_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=back.config.storage_backends.PrivateMediaS3Storage(),
                        upload_to="",
                    ),
                ),
                ("original_url", models.URLField(blank=True, null=True)),
                ("parser", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "knowledge_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="language_model.knowledgebase",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="knowledgeitem",
            name="data_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="language_model.datasource",
            ),
        ),
    ]
