# Generated by Django 4.1.13 on 2024-02-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("language_model", "0046_alter_datasource_original_csv_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ragconfig",
            name="s3_index_path",
            field=models.CharField(
                blank=True, editable=False, max_length=255, null=True
            ),
        ),
    ]
