# Generated by Django 4.1.13 on 2024-04-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("language_model", "0049_remove_ragconfig_index_up_to_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmconfig",
            name="llm_type",
            field=models.CharField(
                choices=[
                    ("vllm", "VLLM Client"),
                    ("openai", "OpenAI Model"),
                    ("claude", "Claude Model"),
                    ("mistral", "Mistral Model"),
                    ("together", "Together Model"),
                ],
                default="openai",
                max_length=10,
            ),
        ),
    ]
