# Generated by Django 4.1.13 on 2024-04-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("language_model", "0050_alter_llmconfig_llm_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ragconfig",
            name="disabled",
        ),
        migrations.AddField(
            model_name="ragconfig",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
    ]
