# Generated by Django 4.1.13 on 2024-04-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("language_model", "0051_remove_ragconfig_disabled_ragconfig_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="ragconfig",
            name="num_replicas",
            field=models.IntegerField(default=1),
        ),
    ]
