# Generated by Django 4.1.13 on 2024-05-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("language_model", "0052_ragconfig_num_replicas"),
    ]

    operations = [
        migrations.CreateModel(
            name="RayTaskState",
            fields=[
                (
                    "task_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("attempt_number", models.IntegerField(default=1)),
                ("name", models.CharField(max_length=255)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("NIL", "NIL"),
                            ("PENDING_ARGS_AVAIL", "PENDING_ARGS_AVAIL"),
                            ("PENDING_NODE_ASSIGNMENT", "PENDING_NODE_ASSIGNMENT"),
                            (
                                "PENDING_OBJ_STORE_MEM_AVAIL",
                                "PENDING_OBJ_STORE_MEM_AVAIL",
                            ),
                            ("PENDING_ARGS_FETCH", "PENDING_ARGS_FETCH"),
                            ("SUBMITTED_TO_WORKER", "SUBMITTED_TO_WORKER"),
                            ("RUNNING", "RUNNING"),
                            ("RUNNING_IN_RAY_GET", "RUNNING_IN_RAY_GET"),
                            ("RUNNING_IN_RAY_WAIT", "RUNNING_IN_RAY_WAIT"),
                            ("FINISHED", "FINISHED"),
                            ("FAILED", "FAILED"),
                        ],
                        max_length=255,
                    ),
                ),
                ("job_id", models.CharField(blank=True, max_length=255, null=True)),
                ("actor_id", models.CharField(blank=True, max_length=255, null=True)),
                ("type", models.CharField(default="PARSE_TASK", max_length=255)),
                ("func_or_class_name", models.CharField(max_length=255)),
                (
                    "parent_task_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("node_id", models.CharField(blank=True, max_length=255, null=True)),
                ("worker_id", models.CharField(blank=True, max_length=255, null=True)),
                ("worker_pid", models.IntegerField(blank=True, null=True)),
                ("error_type", models.CharField(blank=True, max_length=255, null=True)),
                ("language", models.CharField(blank=True, max_length=255, null=True)),
                ("required_resources", models.JSONField(blank=True, null=True)),
                ("runtime_env_info", models.JSONField(blank=True, null=True)),
                (
                    "placement_group_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("events", models.JSONField(blank=True, null=True)),
                ("profiling_data", models.JSONField(blank=True, null=True)),
                ("creation_time_ms", models.IntegerField(blank=True, null=True)),
                ("start_time_ms", models.IntegerField(blank=True, null=True)),
                ("end_time_ms", models.IntegerField(blank=True, null=True)),
                ("task_log_info", models.JSONField(blank=True, null=True)),
                (
                    "error_message",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_debugger_paused", models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
