# Generated by Django 4.1.13 on 2024-05-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("language_model", "0053_raytaskstate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasource",
            name="splitter",
            field=models.CharField(
                choices=[
                    ("sentences", "Sentences"),
                    ("words", "Words"),
                    ("tokens", "Tokens"),
                ],
                default="sentences",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="raytaskstate",
            name="state",
            field=models.CharField(
                choices=[
                    ("NIL", "NIL"),
                    ("PENDING_ARGS_AVAIL", "PENDING_ARGS_AVAIL"),
                    ("PENDING_NODE_ASSIGNMENT", "PENDING_NODE_ASSIGNMENT"),
                    ("PENDING_OBJ_STORE_MEM_AVAIL", "PENDING_OBJ_STORE_MEM_AVAIL"),
                    ("PENDING_ARGS_FETCH", "PENDING_ARGS_FETCH"),
                    ("SUBMITTED_TO_WORKER", "SUBMITTED_TO_WORKER"),
                    ("RUNNING", "RUNNING"),
                    ("RUNNING_IN_RAY_GET", "RUNNING_IN_RAY_GET"),
                    ("RUNNING_IN_RAY_WAIT", "RUNNING_IN_RAY_WAIT"),
                    ("FINISHED", "FINISHED"),
                    ("FAILED", "FAILED"),
                ],
                default="NIL",
                max_length=255,
            ),
        ),
    ]
