# Generated by Django 4.1.13 on 2024-06-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "language_model",
            "0055_rename_system_prefix_historicalpromptconfig_system_prompt_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generationconfig",
            name="max_new_tokens",
        ),
        migrations.RemoveField(
            model_name="generationconfig",
            name="repetition_penalty",
        ),
        migrations.RemoveField(
            model_name="generationconfig",
            name="top_k",
        ),
        migrations.RemoveField(
            model_name="generationconfig",
            name="top_p",
        ),
        migrations.AddField(
            model_name="generationconfig",
            name="max_tokens",
            field=models.IntegerField(default=1024),
        ),
    ]