# Generated by Django 4.1.13 on 2024-06-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_model', '0057_remove_llmconfig_ggml_llm_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intent',
            name='intent_name',
            field=models.CharField(max_length=255),
        ),
    ]
