# Generated by Django 4.1.13 on 2024-07-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("language_model", "0058_alter_intent_intent_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmconfig",
            name="enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="llmconfig",
            name="num_replicas",
            field=models.IntegerField(default=1),
        ),
    ]
