# Generated by Django 4.1.13 on 2024-08-22 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("language_model", "0059_llmconfig_enabled_llmconfig_num_replicas"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="embedding",
            name="rag_config",
        ),
        migrations.AddField(
            model_name="embedding",
            name="retriever_config",
            field=models.ForeignKey(
                default=1,
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="language_model.retrieverconfig",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="retrieverconfig",
            name="enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="retrieverconfig",
            name="index_status",
            field=models.CharField(
                choices=[
                    ("no_index", "No Index"),
                    ("outdated", "Outdated"),
                    ("up_to_date", "Up to Date"),
                ],
                default="no_index",
                editable=False,
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="retrieverconfig",
            name="knowledge_base",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="language_model.knowledgebase",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="retrieverconfig",
            name="num_replicas",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="retrieverconfig",
            name="s3_index_path",
            field=models.CharField(
                blank=True, editable=False, max_length=255, null=True
            ),
        ),
        migrations.DeleteModel(
            name="RAGConfig",
        ),
    ]
