# Generated by Django 4.1.13 on 2024-09-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("language_model", "0060_remove_embedding_rag_config_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalpromptconfig",
            name="n_contexts_to_use",
        ),
        migrations.RemoveField(
            model_name="historicalpromptconfig",
            name="system_prompt",
        ),
        migrations.RemoveField(
            model_name="promptconfig",
            name="n_contexts_to_use",
        ),
        migrations.RemoveField(
            model_name="promptconfig",
            name="system_prompt",
        ),
        migrations.AddField(
            model_name="historicalpromptconfig",
            name="prompt",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="promptconfig",
            name="prompt",
            field=models.TextField(default=""),
        ),
    ]
