# Generated by Django 4.1.13 on 2024-10-04 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "language_model",
            "0061_remove_historicalpromptconfig_n_contexts_to_use_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalRetrieverConfig",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_date", models.DateTimeField(blank=True, editable=False)),
                ("updated_date", models.DateTimeField(blank=True, editable=False)),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "model_name",
                    models.CharField(default="colbert-ir/colbertv2.0", max_length=255),
                ),
                (
                    "retriever_type",
                    models.CharField(
                        choices=[
                            ("colbert", "ColBERT Search"),
                            ("e5", "Standard Semantic Search"),
                        ],
                        default="colbert",
                        max_length=10,
                    ),
                ),
                (
                    "index_status",
                    models.CharField(
                        choices=[
                            ("no_index", "No Index"),
                            ("outdated", "Outdated"),
                            ("up_to_date", "Up to Date"),
                        ],
                        default="no_index",
                        editable=False,
                        max_length=20,
                    ),
                ),
                (
                    "s3_index_path",
                    models.CharField(
                        blank=True, editable=False, max_length=255, null=True
                    ),
                ),
                ("batch_size", models.IntegerField(default=1)),
                (
                    "device",
                    models.CharField(
                        choices=[("cpu", "CPU"), ("cuda", "GPU")],
                        default="cpu",
                        max_length=10,
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("num_replicas", models.IntegerField(default=1)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "knowledge_base",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="language_model.knowledgebase",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical retriever config",
                "verbose_name_plural": "historical retriever configs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalLLMConfig",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_date", models.DateTimeField(blank=True, editable=False)),
                ("updated_date", models.DateTimeField(blank=True, editable=False)),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "llm_type",
                    models.CharField(
                        choices=[
                            ("vllm", "VLLM Client"),
                            ("openai", "OpenAI Model"),
                            ("claude", "Claude Model"),
                            ("mistral", "Mistral Model"),
                            ("together", "Together Model"),
                        ],
                        default="openai",
                        max_length=10,
                    ),
                ),
                ("llm_name", models.CharField(default="gpt-4o", max_length=100)),
                ("base_url", models.CharField(blank=True, max_length=255, null=True)),
                ("model_max_length", models.IntegerField(blank=True, null=True)),
                ("enabled", models.BooleanField(default=False)),
                ("num_replicas", models.IntegerField(default=1)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical llm config",
                "verbose_name_plural": "historical llm configs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalGenerationConfig",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_date", models.DateTimeField(blank=True, editable=False)),
                ("updated_date", models.DateTimeField(blank=True, editable=False)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("temperature", models.FloatField(default=0.2)),
                ("max_tokens", models.IntegerField(default=1024)),
                ("seed", models.IntegerField(default=42)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical generation config",
                "verbose_name_plural": "historical generation configs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
