# Generated by Django 4.1.13 on 2024-11-13 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "language_model",
            "0062_historicalretrieverconfig_historicalllmconfig_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledgeitem",
            name="data_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="language_model.datasource",
            ),
        ),
    ]
