# Generated by Django 4.2.17 on 2024-12-19 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language_model', '0063_alter_knowledgeitem_data_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retrieverconfig',
            name='knowledge_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language_model.knowledgebase'),
        ),
    ]
