# Generated by Django 4.2.16 on 2024-12-30 16:54

import django.db.models.deletion
from django.db import migrations, models


def delete_null_knowledge_base_configs(apps, schema_editor):
    RetrieverConfig = apps.get_model('language_model', 'RetrieverConfig')
    RetrieverConfig.objects.filter(knowledge_base__isnull=True).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("language_model", "0063_alter_knowledgeitem_data_source"),
    ]
    operations = [
        migrations.RunPython(
            delete_null_knowledge_base_configs,
            reverse_code=migrations.RunPython.noop
        ),
    ]
