# Generated by Django 4.2.17 on 2025-01-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_model', '0064_alter_retrieverconfig_knowledge_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='strategy',
            field=models.CharField(choices=[('no_parsing', 'No Parsing'), ('auto', 'Auto'), ('fast', 'Fast'), ('ocr_only', 'OCR Only'), ('hi_res', 'Hi Res')], default='no_parsing', max_length=10),
        ),
    ]
