# Generated by Django 4.2.17 on 2025-02-03 18:24

import back.utils.encrypt._django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language_model', '0066_alter_historicalllmconfig_llm_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalllmconfig',
            name='api_key',
            field=back.utils.encrypt._django.NissaStringField(blank=True, editable=True, help_text='Optional API key for the LLM. This value will be stored encrypted.', null=True),
        ),
        migrations.AddField(
            model_name='llmconfig',
            name='api_key',
            field=back.utils.encrypt._django.NissaStringField(blank=True, editable=True, help_text='Optional API key for the LLM. This value will be stored encrypted.', null=True),
        ),
    ]
