# Generated by Django 4.2.17 on 2025-01-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_model', '0066_alter_datasource_strategy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalllmconfig',
            name='llm_type',
            field=models.CharField(choices=[('vllm', 'VLLM Client'), ('openai', 'OpenAI Model'), ('claude', 'Claude Model'), ('mistral', 'Mistral Model'), ('together', 'Together Model'), ('gemini', 'Gemini Model')], default='openai', max_length=10),
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='llm_type',
            field=models.CharField(choices=[('vllm', 'VLLM Client'), ('openai', 'OpenAI Model'), ('claude', 'Claude Model'), ('mistral', 'Mistral Model'), ('together', 'Together Model'), ('gemini', 'Gemini Model')], default='openai', max_length=10),
        ),
    ]
