# Generated by Django 4.2.17 on 2025-02-18 15:08

import back.utils.encrypt._django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language_model', '0068_historicalllmconfig_api_key_llmconfig_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalllmconfig',
            name='api_key',
            field=back.utils.encrypt._django.NissaStringField(blank=True, editable=True, help_text='Optional API key for the LLM. This value will be stored encrypted. Note: API keys can only be saved when encryption is properly configured.', null=True),
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='api_key',
            field=back.utils.encrypt._django.NissaStringField(blank=True, editable=True, help_text='Optional API key for the LLM. This value will be stored encrypted. Note: API keys can only be saved when encryption is properly configured.', null=True),
        ),
    ]
