import csv

from rest_framework import serializers

from back.apps.language_model.models.data import KnowledgeBase, KnowledgeItem, AutoGeneratedTitle


class KnowledgeBaseSerializer(serializers.ModelSerializer):
    MANDATORY_COLUMNS = ["title", "content", "url"]

    class Meta:
        model = KnowledgeBase
        fields = "__all__"

    # extra step when validating CSVs: the file must contain the following columns: title, content, url
    def validate(self, data):
        if "original_csv" in data:
            f = data["original_csv"]
            decoded_file = f.read().decode("utf-8").splitlines()
            reader = csv.DictReader(decoded_file)
            if not all(elem in reader.fieldnames for elem in self.MANDATORY_COLUMNS):
                raise serializers.ValidationError(
                    "The file must contain the following columns: "
                    + ", ".join(self.MANDATORY_COLUMNS)
                )
            f.seek(0)
        return data


class KnowledgeBaseFromUrlSerializer(KnowledgeBaseSerializer):
    url = serializers.URLField()

    class Meta:
        model = KnowledgeBase
        fields = ["name", "lang", "url"]


class KnowledgeItemSerializer(serializers.ModelSerializer):
    class Meta:
        model = KnowledgeItem
        fields = "__all__"


class AutoGeneratedTitleSerializer(serializers.ModelSerializer):
    class Meta:
        model = AutoGeneratedTitle
        fields = "__all__"
