[tool.poetry]
name = "back"
version = "0.1.0"
description = ""
authors = ["Hector Soria <hector.soria@with-madrid.com>"]
license = "Proprietary"

packages = [
    {include = "back"},
]

[tool.poetry.dependencies]
python = "~3.13"
modelw-preset-django = {version = "*", extras = ["health"]}
drf-spectacular = {extras = ["sidecar"], version = "*"}
channels = "*"
daphne = "*"
Django = "*"
django-cors-headers = "*"
django-extensions = "*"
django-better-admin-arrayfield = "*"
requests = "*"
python-json-logger = "*"
psycopg2 = "*"
whitenoise = "*"
python-dotenv = "*"
httpx = "*"
myst-parser = "*"
django-rest-knox = "*"
pgvector = "*"
django-filter = "*"
django-storages = "*"
sqlalchemy = "*"
gevent = "*"
boto3 = "*"
djfernet = "*"
scrapy = "*"
scrapy-playwright = "*"
undetected-playwright = "*"
django-simple-history = "*"
crochet = "*"
pillow = "*"
memray = "*"
gunicorn = "*"
uvicorn = "*"
PyMuPDF = "*"
channels-redis = "*"
typefit = "*"
ray = {extras = ["data", "serve"], version = "*"}
chat-rag = "*"
networkx = "*"
markdown = "*"
procrastinate = "*"
[tool.poetry.group.dev.dependencies]
black = "*"
isort = "*"
ipython = "*"

[tool.poetry.group.doc.dependencies]
sphinx = "<6"

[tool.isort]
profile = "black"
known_first_party = "back"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "test"
url = "https://test.pypi.org/simple/"
priority = "explicit"