# Generated by Django 4.1.7 on 2023-12-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OK", "OK"),
                            ("WARNING", "WARNING"),
                            ("ERROR", "ERROR"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "root_cause_code",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("root_cause_message", models.TextField(blank=True, default="")),
                ("root_cause_details", models.TextField(blank=True, default="")),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("event_type", models.CharField(max_length=255)),
                ("is_success", models.BooleanField()),
                ("data", models.JSONField()),
            ],
            options={
                "ordering": ["-date_created"],
                "index_together": {("event_type", "date_created")},
            },
        ),
    ]
