# Generated by Django 4.1.4 on 2022-12-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("broker", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="payload",
        ),
        migrations.AddField(
            model_name="message",
            name="stacks",
            field=models.JSONField(null=True),
        ),
    ]
