# Generated by Django 4.1.4 on 2023-01-10 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("broker", "0006_rpcresponse"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RPCResponse",
        ),
    ]
