# Generated by Django 4.1.4 on 2023-02-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="rpc_group",
            field=models.BooleanField(
                default=False, verbose_name="Belongs to the RPC group?"
            ),
        ),
    ]
