# Generated by Django 4.1.4 on 2023-03-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0002_user_rpc_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="rpc_group",
            field=models.BooleanField(
                default=False, verbose_name="Belongs to the RPC group? [y/N]"
            ),
        ),
    ]
