# Generated by Django 4.1.13 on 2023-12-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0003_alter_user_rpc_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="remember_me",
            field=models.UUIDField(
                blank=True, editable=False, null=True, verbose_name="remember me"
            ),
        ),
    ]
