# Generated by Django 4.1.13 on 2023-12-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0004_user_remember_me"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="remember_me",
            field=models.TextField(
                blank=True, editable=False, null=True, verbose_name="remember me"
            ),
        ),
    ]
