# Generated by Django 5.1.11 on 2025-08-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0005_alter_user_remember_me"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                db_collation="und-x-icu",
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
    ]
