# Generated by Django 5.2.6 on 2025-11-18 00:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0006_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sender_uuid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Universal sender identifier for lefebvre-chatfaq integration",
                unique=True,
            ),
        ),
    ]
