# Generated by Django 5.2.6 on 2025-11-18 00:00

import uuid
from django.db import migrations, models


def create_uuid(apps, schema_editor):
    User = apps.get_model("people", "User")
    for user in User.objects.all():
        user.sender_uuid = uuid.uuid4()
        user.save(update_fields=["sender_uuid"])

class Migration(migrations.Migration):

    dependencies = [
        ("people", "0006_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sender_uuid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Universal sender identifier for lefebvre-chatfaq integration",
                null=True,  # Change unique=True to null=True here
            ),
        ),
        migrations.RunPython(create_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="user",
            name="sender_uuid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Universal sender identifier for lefebvre-chatfaq integration",
                unique=True,  # This one remains unique=True
            ),
        ),
    ]
