FROM rayproject/ray:latest-py310-cpu

USER root

RUN apt-get update && \
    apt-get install -y --no-install-recommends g++ curl ffmpeg libsm6 libxext6 && \
    rm -rf /var/lib/apt/lists/*

USER ray

RUN pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple chat-rag==0.1.64 --no-cache-dir