from django.contrib import admin

from .forms import PromptConfigForm
from simple_history.admin import SimpleHistoryAdmin

from .models.data import KnowledgeBase, KnowledgeItem, Embedding, AutoGeneratedTitle
from .models.rag_pipeline import RAGConfig, LLMConfig, PromptConfig, GenerationConfig, RetrieverConfig


class PromptConfigAdmin(SimpleHistoryAdmin):
    form = PromptConfigForm


class KnowledgeItemAdmin(admin.ModelAdmin):
    list_display = ["content", "url"]
    list_filter = ["knowledge_base"]


admin.site.register(RAGConfig)
admin.site.register(KnowledgeBase)
admin.site.register(KnowledgeItem, KnowledgeItemAdmin)
admin.site.register(AutoGeneratedTitle)
admin.site.register(LLMConfig)
admin.site.register(PromptConfig, PromptConfigAdmin)
admin.site.register(GenerationConfig)
admin.site.register(RetrieverConfig)
admin.site.register(Embedding)
