import csv

from rest_framework import serializers

from .models import KnowledgeBase, KnowledgeItem, RAGConfig, LLMConfig, GenerationConfig, PromptConfig, AutoGeneratedTitle


class KnowledgeBaseSerializer(serializers.ModelSerializer):
    MANDATORY_COLUMNS = ["title", "content", "url"]

    class Meta:
        model = KnowledgeBase
        fields = "__all__"

    # extra step when validating CSVs: the file must contain the following columns: intent, answer, url
    def validate(self, data):
        if "original_csv" in data:
            f = data["original_csv"]
            decoded_file = f.read().decode("utf-8").splitlines()
            reader = csv.DictReader(decoded_file)
            if not all(elem in reader.fieldnames for elem in self.MANDATORY_COLUMNS):
                raise serializers.ValidationError(
                    "The file must contain the following columns: "
                    + ", ".join(self.MANDATORY_COLUMNS)
                )
            f.seek(0)
        return data


class KnowledgeBaseFromUrlSerializer(KnowledgeBaseSerializer):
    url = serializers.URLField()

    class Meta:
        model = KnowledgeBase
        fields = ["name", "lang", "url"]


class KnowledgeItemSerializer(serializers.ModelSerializer):
    class Meta:
        model = KnowledgeItem
        fields = "__all__"


class AutoGeneratedTitleSerializer(serializers.ModelSerializer):
    class Meta:
        model = AutoGeneratedTitle
        fields = "__all__"


class RAGConfigSerializer(serializers.ModelSerializer):
    class Meta:
        model = RAGConfig
        fields = "__all__"


class LLMConfigSerializer(serializers.ModelSerializer):
    status = serializers.CharField(read_only=True)

    class Meta:
        model = LLMConfig
        fields = "__all__"


class GenerationConfigSerializer(serializers.ModelSerializer):
    class Meta:
        model = GenerationConfig
        fields = "__all__"


class PromptConfigSerializer(serializers.ModelSerializer):
    class Meta:
        model = PromptConfig
        fields = "__all__"
