from rest_framework.routers import DefaultRouter

from . import views

router = DefaultRouter()
router.register(r"knowledge_bases", views.KnowledgeBaseAPIViewSet, basename="knowledge_base")
router.register(r"knowledge_items", views.KnowledgeItemAPIViewSet, basename="item")
router.register(r"autogenerated_titles", views.AutoGeneratedTitleAPIViewSet, basename="utterance")
router.register(r"llm_configs", views.LLMConfigAPIViewSet, basename="llm_config")
router.register(r"rag_configs", views.RAGConfigAPIViewSet, basename="rag_config")
router.register(r"generation_configs", views.GenerationConfigAPIViewSet, basename="generation_config")
router.register(r"prompt_configs", views.PromptConfigAPIViewSet, basename="prompt_config")

urlpatterns = router.urls
