# Generated by Django 4.1.4 on 2022-12-21 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fsm", "0001_initial"),
        ("broker", "0002_remove_message_payload_message_stacks"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformBot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "platform_type",
                    models.CharField(
                        choices=[("telegram", "telegram"), ("ws", "ws")], max_length=255
                    ),
                ),
                ("platform_meta", models.JSONField(default=dict)),
                (
                    "fsm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fsm.finitestatemachine",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
