# Generated by Django 4.1.4 on 2022-12-22 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("broker", "0003_platformbot"),
    ]

    operations = [
        migrations.RenameField(
            model_name="platformbot",
            old_name="fsm",
            new_name="fsm_def",
        ),
    ]
