# Generated by Django 4.1.4 on 2023-01-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("broker", "0005_rename_platformbot_platformconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="RPCResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("ctx", models.JSONField(default=dict)),
                ("payload", models.JSONField(default=dict)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
