# Generated by Django 4.1.4 on 2023-01-23 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("broker", "0007_delete_rpcresponse"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomWSPlatformConfig",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("broker.platformconfig",),
        ),
        migrations.CreateModel(
            name="TelegramPlatformConfig",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("broker.platformconfig",),
        ),
        migrations.RemoveField(
            model_name="platformconfig",
            name="fsm_def",
        ),
    ]
