# Generated by Django 4.1.4 on 2023-03-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("broker", "0010_delete_platformconfig_delete_customwsplatformconfig_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="conversation_name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
