# Generated by Django 4.1.7 on 2023-04-19 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("broker", "0012_vote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="message",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="broker.message",
            ),
        ),
    ]
