# Generated by Django 4.1.9 on 2023-05-19 11:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("broker", "0014_alter_vote_value"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="transmitter",
            new_name="sender",
        ),
    ]
