# Generated by Django 4.1.9 on 2023-05-19 12:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("broker", "0015_rename_transmitter_message_sender"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Vote",
            new_name="UserFeedback",
        ),
    ]
