# Generated by Django 4.1.9 on 2023-05-19 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("broker", "0016_rename_vote_userfeedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "value",
                    models.CharField(
                        choices=[("positive", "Positive"), ("negative", "Negative")],
                        max_length=255,
                    ),
                ),
                ("feedback", models.TextField()),
                (
                    "message",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="broker.message",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
