# Generated by Django 4.1.9 on 2023-05-19 15:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("broker", "0017_adminreview"),
    ]

    operations = [
        migrations.RenameField(
            model_name="adminreview",
            old_name="feedback",
            new_name="review",
        ),
    ]
