# Generated by Django 4.1.9 on 2023-05-26 13:32

from django.db import migrations, models
import django.db.models.deletion


def clear_messages(apps, scheme_editor):
    Message = apps.get_model('broker', 'Message')
    Message.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("broker", "0018_rename_feedback_adminreview_review"),
    ]

    operations = [
        migrations.RunSQL('SET CONSTRAINTS ALL IMMEDIATE;'),
        migrations.RunPython(clear_messages),
        migrations.RunSQL('SET CONSTRAINTS ALL DEFERRED;'),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "platform_conversation_id",
                    models.CharField(max_length=255, unique=True),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="message",
            name="conversation_name",
        ),
        migrations.AlterField(
            model_name="message",
            name="prev",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="broker.message",
            ),
        ),
        migrations.RemoveField(
            model_name="message",
            name="conversation",
        ),
        migrations.AddField(
            model_name="message",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="broker.conversation"
            ),
        ),
    ]
