# Generated by Django 4.1.9 on 2023-05-26 14:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("broker", "0019_conversation_remove_message_conversation_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="title",
        ),
    ]
