# Generated by Django 4.1.9 on 2023-05-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("broker", "0020_remove_conversation_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfeedback",
            name="feedback",
            field=models.TextField(blank=True, null=True),
        ),
    ]
