# Generated by Django 4.1.9 on 2023-06-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("broker", "0021_alter_userfeedback_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="RPCConsumerRoundRobinQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("rpc_group_name", models.CharField(max_length=255, unique=True)),
                ("fsm_id", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
