# Generated by Django 4.1.9 on 2023-06-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("broker", "0022_rpcconsumerroundrobinqueue"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="stacks",
            new_name="stack",
        ),
        migrations.AddField(
            model_name="message",
            name="stack_id",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
