# Generated by Django 4.1.9 on 2023-06-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("broker", "0023_rename_stacks_message_stack_message_stack_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="last",
            field=models.BooleanField(default=False),
        ),
    ]
