# Generated by Django 4.1.9 on 2023-06-30 12:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("broker", "0024_message_last"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rpcconsumerroundrobinqueue",
            old_name="rpc_group_name",
            new_name="layer_group_name",
        ),
        migrations.RenameField(
            model_name="rpcconsumerroundrobinqueue",
            old_name="fsm_id",
            new_name="rr_group_key",
        ),
    ]
