# Generated by Django 4.1.9 on 2023-06-30 12:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "broker",
            "0025_rename_rpc_group_name_rpcconsumerroundrobinqueue_layer_group_name_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RPCConsumerRoundRobinQueue",
            new_name="ConsumerRoundRobinQueue",
        ),
    ]
