# Generated by Django 4.1.13 on 2024-01-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("broker", "0026_rename_rpcconsumerroundrobinqueue_consumerroundrobinqueue"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adminreview",
            name="value",
        ),
        migrations.AddField(
            model_name="adminreview",
            name="data",
            field=models.JSONField(default=dict),
        ),
    ]
