# Generated by Django 4.1.13 on 2024-01-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("broker", "0027_remove_adminreview_value_adminreview_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminreview",
            name="data",
            field=models.JSONField(default=list),
        ),
    ]
