# Generated by Django 4.1.13 on 2024-01-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("broker", "0028_alter_adminreview_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminreview",
            name="review",
            field=models.TextField(blank=True, null=True),
        ),
    ]
