# Generated by Django 4.1.13 on 2024-01-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("broker", "0031_adminreview_gen_review_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminreview",
            name="ki_review_data",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
