# Generated by Django 4.1.13 on 2024-01-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("broker", "0032_alter_adminreview_ki_review_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="RemoteSDKParsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("layer_group_name", models.CharField(max_length=255)),
                ("parser_name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
