# Generated by Django 4.1.13 on 2024-09-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("broker", "0034_rename_feedback_userfeedback_feedback_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="stack_group_id",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
