# Generated by Django 4.1.13 on 2024-11-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("broker", "0035_message_stack_group_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="persistent_context",
            field=models.JSONField(default=dict),
        ),
    ]
