# Generated by Django 4.1.13 on 2024-11-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("broker", "0036_message_persistent_context"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="persistent_context",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
