# Generated by Django 4.1.13 on 2024-11-12 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("broker", "0037_alter_message_persistent_context"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="persistent_context",
            new_name="status",
        ),
    ]
