# Generated by Django 4.1.13 on 2024-11-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("broker", "0038_rename_persistent_context_message_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="authentication_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="conversation",
            name="initial_conversation_metadata",
            field=models.JSONField(default=dict),
        ),
    ]
