# Generated by Django 4.1.13 on 2024-11-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("broker", "0039_conversation_authentication_required_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="last_chunk",
            field=models.BooleanField(default=False),
        ),
    ]
