# Generated by Django 4.2.17 on 2024-12-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0040_message_last_chunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='upload_path',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
