# Generated by Django 4.2.16 on 2024-12-31 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("broker", "0043_userfeedback_star_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfeedback",
            name="message",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="broker.message",
            ),
        ),
    ]
