# Generated by Django 4.2.16 on 2025-01-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("broker", "0044_alter_userfeedback_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="fsm_state",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
