# Generated by Django 4.2.18 on 2025-01-23 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("broker", "0045_message_fsm_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userfeedback",
            name="feedback_comment",
        ),
        migrations.RemoveField(
            model_name="userfeedback",
            name="feedback_selection",
        ),
        migrations.RemoveField(
            model_name="userfeedback",
            name="message",
        ),
        migrations.RemoveField(
            model_name="userfeedback",
            name="star_rating",
        ),
        migrations.RemoveField(
            model_name="userfeedback",
            name="star_rating_max",
        ),
        migrations.RemoveField(
            model_name="userfeedback",
            name="value",
        ),
        migrations.AddField(
            model_name="userfeedback",
            name="feedback_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userfeedback",
            name="message_source",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_userfeedback_set",
                to="broker.message",
            ),
        ),
        migrations.AddField(
            model_name="userfeedback",
            name="message_target",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="target_userfeedback_set",
                to="broker.message",
            ),
        ),
    ]
