# Generated by Django 4.2.17 on 2025-02-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0046_remove_userfeedback_feedback_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='fsm_state_override',
            field=models.TextField(blank=True, null=True),
        ),
    ]
